{
  imports = [
    ./hypr
    ./bash.nix
    ./git.nix
    ./theme.nix
    ./mako.nix
    ./udiskie.nix
    ./spicetify.nix
    ./ghostty.nix
    ./vscode.nix
    ./mime.nix
    ./rofi.nix
    ./virtualisation.nix
    ./cliphist.nix
    ./nixcord.nix
    ./zen-browser.nix
    ./scripts
    ./themes
  ];
}